### ISSUE TITLE
error 9.02

### ISSUE THREAD

**Issue by raineday** [lorikrell/hn-wconquest#18]
1x ...ns\HandyNotes_WarcraftConquest\Utils\utils-icons.lua:7: attempt to call global 'GetAtlasInfo' (a nil value)
[string "@HandyNotes_WarcraftConquest\Utils\utils-icons.lua"]:7: in function `atlas'
[string "@HandyNotes_WarcraftConquest\Const\const-icons.lua"]:11: in main chunk

Locals:
atlas = "ShipMissionIcon-Legendary-Map"
scale = 2.500000
(*temporary) = nil
(*temporary) = "ShipMissionIcon-Legendary-Map"
(*temporary) = "attempt to call global 'GetAtlasInfo' (a nil value)"

**Comment by lorikrell** [comment]
Fixed with version 1.4.0!
